import { PrismaClient } from '@prisma/client'

const prisma = new PrismaClient()

const COUNTRIES = [
  { name: 'Afghanistan', code: 'AF' },
  { name: 'Albania', code: 'AL' },
  { name: 'Algeria', code: 'DZ' },
  { name: 'Andorra', code: 'AD' },
  { name: 'Angola', code: 'AO' },
  { name: 'Antigua and Barbuda', code: 'AG' },
  { name: 'Argentina', code: 'AR' },
  { name: 'Armenia', code: 'AM' },
  { name: 'Australia', code: 'AU' },
  { name: 'Austria', code: 'AT' },
  { name: 'Azerbaijan', code: 'AZ' },
  { name: 'Bahamas', code: 'BS' },
  { name: 'Bahrain', code: 'BH' },
  { name: 'Bangladesh', code: 'BD' },
  { name: 'Barbados', code: 'BB' },
  { name: 'Belarus', code: 'BY' },
  { name: 'Belgium', code: 'BE' },
  { name: 'Belize', code: 'BZ' },
  { name: 'Benin', code: 'BJ' },
  { name: 'Bhutan', code: 'BT' },
  { name: 'Bolivia', code: 'BO' },
  { name: 'Bosnia and Herzegovina', code: 'BA' },
  { name: 'Botswana', code: 'BW' },
  { name: 'Brazil', code: 'BR' },
  { name: 'Brunei', code: 'BN' },
  { name: 'Bulgaria', code: 'BG' },
  { name: 'Burkina Faso', code: 'BF' },
  { name: 'Burundi', code: 'BI' },
  { name: 'Cambodia', code: 'KH' },
  { name: 'Cameroon', code: 'CM' },
  { name: 'Canada', code: 'CA' },
  { name: 'Cape Verde', code: 'CV' },
  { name: 'Central African Republic', code: 'CF' },
  { name: 'Chad', code: 'TD' },
  { name: 'Chile', code: 'CL' },
  { name: 'China', code: 'CN' },
  { name: 'Colombia', code: 'CO' },
  { name: 'Comoros', code: 'KM' },
  { name: 'Congo', code: 'CG' },
  { name: 'Costa Rica', code: 'CR' },
  { name: 'Croatia', code: 'HR' },
  { name: 'Cuba', code: 'CU' },
  { name: 'Cyprus', code: 'CY' },
  { name: 'Czech Republic', code: 'CZ' },
  { name: 'Denmark', code: 'DK' },
  { name: 'Djibouti', code: 'DJ' },
  { name: 'Dominican Republic', code: 'DO' },
  { name: 'DR Congo', code: 'CD' },
  { name: 'Ecuador', code: 'EC' },
  { name: 'Egypt', code: 'EG' },
  { name: 'El Salvador', code: 'SV' },
  { name: 'Eritrea', code: 'ER' },
  { name: 'Estonia', code: 'EE' },
  { name: 'Eswatini', code: 'SZ' },
  { name: 'Ethiopia', code: 'ET' },
  { name: 'Fiji', code: 'FJ' },
  { name: 'Finland', code: 'FI' },
  { name: 'France', code: 'FR' },
  { name: 'Gabon', code: 'GA' },
  { name: 'Gambia', code: 'GM' },
  { name: 'Georgia', code: 'GE' },
  { name: 'Germany', code: 'DE' },
  { name: 'Ghana', code: 'GH' },
  { name: 'Greece', code: 'GR' },
  { name: 'Guatemala', code: 'GT' },
  { name: 'Guinea', code: 'GN' },
  { name: 'Guinea-Bissau', code: 'GW' },
  { name: 'Guyana', code: 'GY' },
  { name: 'Haiti', code: 'HT' },
  { name: 'Honduras', code: 'HN' },
  { name: 'Hungary', code: 'HU' },
  { name: 'Iceland', code: 'IS' },
  { name: 'India', code: 'IN' },
  { name: 'Indonesia', code: 'ID' },
  { name: 'Iran', code: 'IR' },
  { name: 'Iraq', code: 'IQ' },
  { name: 'Ireland', code: 'IE' },
  { name: 'Israel', code: 'IL' },
  { name: 'Italy', code: 'IT' },
  { name: 'Ivory Coast', code: 'CI' },
  { name: 'Jamaica', code: 'JM' },
  { name: 'Japan', code: 'JP' },
  { name: 'Jordan', code: 'JO' },
  { name: 'Kazakhstan', code: 'KZ' },
  { name: 'Kenya', code: 'KE' },
  { name: 'Kuwait', code: 'KW' },
  { name: 'Kyrgyzstan', code: 'KG' },
  { name: 'Laos', code: 'LA' },
  { name: 'Latvia', code: 'LV' },
  { name: 'Lebanon', code: 'LB' },
  { name: 'Lesotho', code: 'LS' },
  { name: 'Liberia', code: 'LR' },
  { name: 'Libya', code: 'LY' },
  { name: 'Liechtenstein', code: 'LI' },
  { name: 'Lithuania', code: 'LT' },
  { name: 'Luxembourg', code: 'LU' },
  { name: 'Madagascar', code: 'MG' },
  { name: 'Malawi', code: 'MW' },
  { name: 'Malaysia', code: 'MY' },
  { name: 'Maldives', code: 'MV' },
  { name: 'Mali', code: 'ML' },
  { name: 'Malta', code: 'MT' },
  { name: 'Mauritania', code: 'MR' },
  { name: 'Mauritius', code: 'MU' },
  { name: 'Mexico', code: 'MX' },
  { name: 'Moldova', code: 'MD' },
  { name: 'Monaco', code: 'MC' },
  { name: 'Mongolia', code: 'MN' },
  { name: 'Montenegro', code: 'ME' },
  { name: 'Morocco', code: 'MA' },
  { name: 'Mozambique', code: 'MZ' },
  { name: 'Myanmar', code: 'MM' },
  { name: 'Namibia', code: 'NA' },
  { name: 'Nepal', code: 'NP' },
  { name: 'Netherlands', code: 'NL' },
  { name: 'New Zealand', code: 'NZ' },
  { name: 'Nicaragua', code: 'NI' },
  { name: 'Niger', code: 'NE' },
  { name: 'Nigeria', code: 'NG' },
  { name: 'North Korea', code: 'KP' },
  { name: 'North Macedonia', code: 'MK' },
  { name: 'Norway', code: 'NO' },
  { name: 'Oman', code: 'OM' },
  { name: 'Pakistan', code: 'PK' },
  { name: 'Palestine', code: 'PS' },
  { name: 'Panama', code: 'PA' },
  { name: 'Papua New Guinea', code: 'PG' },
  { name: 'Paraguay', code: 'PY' },
  { name: 'Peru', code: 'PE' },
  { name: 'Philippines', code: 'PH' },
  { name: 'Poland', code: 'PL' },
  { name: 'Portugal', code: 'PT' },
  { name: 'Qatar', code: 'QA' },
  { name: 'Romania', code: 'RO' },
  { name: 'Russia', code: 'RU' },
  { name: 'Rwanda', code: 'RW' },
  { name: 'Saudi Arabia', code: 'SA' },
  { name: 'Senegal', code: 'SN' },
  { name: 'Serbia', code: 'RS' },
  { name: 'Sierra Leone', code: 'SL' },
  { name: 'Singapore', code: 'SG' },
  { name: 'Slovakia', code: 'SK' },
  { name: 'Slovenia', code: 'SI' },
  { name: 'Somalia', code: 'SO' },
  { name: 'South Africa', code: 'ZA' },
  { name: 'South Korea', code: 'KR' },
  { name: 'South Sudan', code: 'SS' },
  { name: 'Spain', code: 'ES' },
  { name: 'Sri Lanka', code: 'LK' },
  { name: 'Sudan', code: 'SD' },
  { name: 'Sweden', code: 'SE' },
  { name: 'Switzerland', code: 'CH' },
  { name: 'Syria', code: 'SY' },
  { name: 'Taiwan', code: 'TW' },
  { name: 'Tajikistan', code: 'TJ' },
  { name: 'Tanzania', code: 'TZ' },
  { name: 'Thailand', code: 'TH' },
  { name: 'Timor-Leste', code: 'TL' },
  { name: 'Togo', code: 'TG' },
  { name: 'Trinidad and Tobago', code: 'TT' },
  { name: 'Tunisia', code: 'TN' },
  { name: 'Turkey', code: 'TR' },
  { name: 'Turkmenistan', code: 'TM' },
  { name: 'Uganda', code: 'UG' },
  { name: 'Ukraine', code: 'UA' },
  { name: 'United Arab Emirates', code: 'AE' },
  { name: 'United Kingdom', code: 'GB' },
  { name: 'United States', code: 'US' },
  { name: 'Uruguay', code: 'UY' },
  { name: 'Uzbekistan', code: 'UZ' },
  { name: 'Venezuela', code: 'VE' },
  { name: 'Vietnam', code: 'VN' },
  { name: 'Yemen', code: 'YE' },
  { name: 'Zambia', code: 'ZM' },
  { name: 'Zimbabwe', code: 'ZW' },
]

const SUGGESTED_LANGUAGES = [
  { flag: '🇲🇬', label: 'Malagasy', value: 'mg' },
  { flag: '🇫🇷', label: 'French', value: 'fr' },
  { flag: '🇸🇦', label: 'Arabic', value: 'ar' },
  { flag: '🇰🇪', label: 'Swahili', value: 'sw' },
  { flag: '🇵🇰', label: 'Urdu', value: 'ur' },
]

const ALL_LANGUAGES = [
  { flag: '🇦🇫', label: 'Dari / Pashto', value: 'ps' },
  { flag: '🌍', label: 'Afrikaans', value: 'af' },
  { flag: '🇦🇱', label: 'Albanian', value: 'sq' },
  { flag: '🇪🇹', label: 'Amharic', value: 'am' },
  { flag: '🇸🇦', label: 'Arabic', value: 'ar' },
  { flag: '🇦🇲', label: 'Armenian', value: 'hy' },
  { flag: '🇦🇿', label: 'Azerbaijani', value: 'az' },
  { flag: '🇧🇩', label: 'Bengali', value: 'bn' },
  { flag: '🇧🇾', label: 'Belarusian', value: 'be' },
  { flag: '🇧🇦', label: 'Bosnian', value: 'bs' },
  { flag: '🇧🇬', label: 'Bulgarian', value: 'bg' },
  { flag: '🇲🇲', label: 'Burmese', value: 'my' },
  { flag: '🇰🇭', label: 'Khmer', value: 'km' },
  { flag: '🇨🇳', label: 'Chinese (Mandarin)', value: 'zh' },
  { flag: '🇹🇼', label: 'Chinese (Traditional)', value: 'zh-TW' },
  { flag: '🇭🇷', label: 'Croatian', value: 'hr' },
  { flag: '🇨🇿', label: 'Czech', value: 'cs' },
  { flag: '🇩🇰', label: 'Danish', value: 'da' },
  { flag: '🇳🇱', label: 'Dutch', value: 'nl' },
  { flag: '🇺🇸', label: 'English', value: 'en' },
  { flag: '🇪🇪', label: 'Estonian', value: 'et' },
  { flag: '🇪🇹', label: 'Oromo', value: 'om' },
  { flag: '🇵🇭', label: 'Filipino', value: 'tl' },
  { flag: '🇫🇮', label: 'Finnish', value: 'fi' },
  { flag: '🇫🇷', label: 'French', value: 'fr' },
  { flag: '🇬🇪', label: 'Georgian', value: 'ka' },
  { flag: '🇩🇪', label: 'German', value: 'de' },
  { flag: '🇬🇭', label: 'Akan / Twi', value: 'ak' },
  { flag: '🇬🇷', label: 'Greek', value: 'el' },
  { flag: '🇮🇳', label: 'Gujarati', value: 'gu' },
  { flag: '🇭🇹', label: 'Haitian Creole', value: 'ht' },
  { flag: '🇳🇬', label: 'Hausa', value: 'ha' },
  { flag: '🇮🇱', label: 'Hebrew', value: 'he' },
  { flag: '🇮🇳', label: 'Hindi', value: 'hi' },
  { flag: '🇭🇺', label: 'Hungarian', value: 'hu' },
  { flag: '🇮🇸', label: 'Icelandic', value: 'is' },
  { flag: '🇮🇩', label: 'Indonesian', value: 'id' },
  { flag: '🇮🇷', label: 'Persian', value: 'fa' },
  { flag: '🇮🇶', label: 'Kurdish', value: 'ku' },
  { flag: '🇮🇪', label: 'Irish', value: 'ga' },
  { flag: '🇮🇹', label: 'Italian', value: 'it' },
  { flag: '🇯🇵', label: 'Japanese', value: 'ja' },
  { flag: '🇮🇩', label: 'Javanese', value: 'jv' },
  { flag: '🇮🇳', label: 'Kannada', value: 'kn' },
  { flag: '🇰🇿', label: 'Kazakh', value: 'kk' },
  { flag: '🇰🇪', label: 'Swahili', value: 'sw' },
  { flag: '🇰🇷', label: 'Korean', value: 'ko' },
  { flag: '🇱🇦', label: 'Lao', value: 'lo' },
  { flag: '🇱🇻', label: 'Latvian', value: 'lv' },
  { flag: '🇱🇹', label: 'Lithuanian', value: 'lt' },
  { flag: '🇲🇬', label: 'Malagasy', value: 'mg' },
  { flag: '🇲🇾', label: 'Malay', value: 'ms' },
  { flag: '🇮🇳', label: 'Malayalam', value: 'ml' },
  { flag: '🇲🇹', label: 'Maltese', value: 'mt' },
  { flag: '🇳🇵', label: 'Nepali', value: 'ne' },
  { flag: '🇳🇬', label: 'Igbo', value: 'ig' },
  { flag: '🇳🇬', label: 'Yoruba', value: 'yo' },
  { flag: '🇳🇴', label: 'Norwegian', value: 'no' },
  { flag: '🇮🇳', label: 'Odia', value: 'or' },
  { flag: '🇵🇰', label: 'Urdu', value: 'ur' },
  { flag: '🇮🇳', label: 'Punjabi', value: 'pa' },
  { flag: '🇵🇱', label: 'Polish', value: 'pl' },
  { flag: '🇧🇷', label: 'Portuguese', value: 'pt' },
  { flag: '🇷🇴', label: 'Romanian', value: 'ro' },
  { flag: '🇷🇺', label: 'Russian', value: 'ru' },
  { flag: '🇷🇼', label: 'Kinyarwanda', value: 'rw' },
  { flag: '🇷🇸', label: 'Serbian', value: 'sr' },
  { flag: '🇸🇰', label: 'Slovak', value: 'sk' },
  { flag: '🇸🇮', label: 'Slovenian', value: 'sl' },
  { flag: '🇸🇴', label: 'Somali', value: 'so' },
  { flag: '🇿🇦', label: 'Sesotho', value: 'st' },
  { flag: '🇿🇦', label: 'Zulu', value: 'zu' },
  { flag: '🇪🇸', label: 'Spanish', value: 'es' },
  { flag: '🇱🇰', label: 'Sinhala', value: 'si' },
  { flag: '🇸🇪', label: 'Swedish', value: 'sv' },
  { flag: '🇮🇳', label: 'Tamil', value: 'ta' },
  { flag: '🇮🇳', label: 'Telugu', value: 'te' },
  { flag: '🇹🇯', label: 'Tajik', value: 'tg' },
  { flag: '🇹🇭', label: 'Thai', value: 'th' },
  { flag: '🇹🇷', label: 'Turkish', value: 'tr' },
  { flag: '🇹🇲', label: 'Turkmen', value: 'tk' },
  { flag: '🇺🇦', label: 'Ukrainian', value: 'uk' },
  { flag: '🇺🇿', label: 'Uzbek', value: 'uz' },
  { flag: '🇻🇳', label: 'Vietnamese', value: 'vi' },
  { flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', label: 'Welsh', value: 'cy' },
]

async function main() {
  console.log('Seeding countries...')
  for (const c of COUNTRIES) {
    await prisma.country.upsert({
      where: { code: c.code },
      update: { name: c.name },
      create: { name: c.name, code: c.code },
    })
  }
  console.log(`✓ ${COUNTRIES.length} countries seeded`)

  console.log('Seeding languages...')
  const suggestedCodes = new Set(SUGGESTED_LANGUAGES.map((l) => l.value))

  // Suggested first (orderIndex 0–4)
  for (let i = 0; i < SUGGESTED_LANGUAGES.length; i++) {
    const l = SUGGESTED_LANGUAGES[i]
    await prisma.language.upsert({
      where: { code: l.value },
      update: { label: l.label, flag: l.flag, isSuggested: true, orderIndex: i },
      create: { code: l.value, label: l.label, flag: l.flag, isSuggested: true, orderIndex: i },
    })
  }

  // All remaining (orderIndex 100+)
  let idx = 100
  const seen = new Set<string>(SUGGESTED_LANGUAGES.map((l) => l.value))
  for (const l of ALL_LANGUAGES) {
    if (seen.has(l.value)) continue
    seen.add(l.value)
    await prisma.language.upsert({
      where: { code: l.value },
      update: { label: l.label, flag: l.flag, isSuggested: false, orderIndex: idx },
      create: { code: l.value, label: l.label, flag: l.flag, isSuggested: false, orderIndex: idx },
    })
    idx++
  }
  console.log(`✓ ${seen.size} languages seeded`)
}

main()
  .catch((e) => { console.error(e); process.exit(1) })
  .finally(() => prisma.$disconnect())
