export interface Language {
  flag: string
  label: string
  value: string
}

// Pinned at top — target market languages
export const SUGGESTED_LANGUAGES: Language[] = [
  { flag: '🇲🇬', label: 'Malagasy', value: 'mg' },
  { flag: '🇫🇷', label: 'Français', value: 'fr' },
  { flag: '🇸🇦', label: 'العربية', value: 'ar' },
  { flag: '🇰🇪', label: 'Kiswahili', value: 'sw' },
  { flag: '🇵🇰', label: 'اردو', value: 'ur' },
]

// Full world language list (alphabetical)
export const ALL_LANGUAGES: Language[] = [
  { flag: '🇦🇫', label: 'Dari / Pashto', value: 'ps' },
  { flag: '🌍', label: 'Afrikaans', value: 'af' },
  { flag: '🇦🇱', label: 'Shqip', value: 'sq' },
  { flag: '🇪🇹', label: 'Amharic — አማርኛ', value: 'am' },
  { flag: '🇸🇦', label: 'العربية', value: 'ar' },
  { flag: '🇦🇲', label: 'Հայերեն', value: 'hy' },
  { flag: '🇦🇿', label: 'Azərbaycan', value: 'az' },
  { flag: '🇧🇩', label: 'বাংলা', value: 'bn' },
  { flag: '🇧🇾', label: 'Беларуская', value: 'be' },
  { flag: '🇧🇦', label: 'Bosanski', value: 'bs' },
  { flag: '🇧🇬', label: 'Български', value: 'bg' },
  { flag: '🇲🇲', label: 'မြန်မာဘာသာ', value: 'my' },
  { flag: '🇰🇭', label: 'ភាសាខ្មែរ', value: 'km' },
  { flag: '🇨🇳', label: '中文 (普通话)', value: 'zh' },
  { flag: '🇹🇼', label: '中文 (繁體)', value: 'zh-TW' },
  { flag: '🇭🇷', label: 'Hrvatski', value: 'hr' },
  { flag: '🇨🇿', label: 'Čeština', value: 'cs' },
  { flag: '🇩🇰', label: 'Dansk', value: 'da' },
  { flag: '🇳🇱', label: 'Nederlands', value: 'nl' },
  { flag: '🇺🇸', label: 'English', value: 'en' },
  { flag: '🇪🇪', label: 'Eesti', value: 'et' },
  { flag: '🇪🇹', label: 'Oromo', value: 'om' },
  { flag: '🇵🇭', label: 'Filipino', value: 'tl' },
  { flag: '🇫🇮', label: 'Suomi', value: 'fi' },
  { flag: '🇫🇷', label: 'Français', value: 'fr' },
  { flag: '🇬🇪', label: 'ქართული', value: 'ka' },
  { flag: '🇩🇪', label: 'Deutsch', value: 'de' },
  { flag: '🇬🇭', label: 'Akan / Twi', value: 'ak' },
  { flag: '🇬🇷', label: 'Ελληνικά', value: 'el' },
  { flag: '🇮🇳', label: 'ગુજરાતી', value: 'gu' },
  { flag: '🇭🇹', label: 'Kreyòl ayisyen', value: 'ht' },
  { flag: '🇳🇬', label: 'Hausa', value: 'ha' },
  { flag: '🇮🇱', label: 'עברית', value: 'he' },
  { flag: '🇮🇳', label: 'हिन्दी', value: 'hi' },
  { flag: '🇭🇺', label: 'Magyar', value: 'hu' },
  { flag: '🇮🇸', label: 'Íslenska', value: 'is' },
  { flag: '🇮🇩', label: 'Bahasa Indonesia', value: 'id' },
  { flag: '🇮🇷', label: 'فارسی', value: 'fa' },
  { flag: '🇮🇶', label: 'کوردی', value: 'ku' },
  { flag: '🇮🇪', label: 'Gaeilge', value: 'ga' },
  { flag: '🇮🇹', label: 'Italiano', value: 'it' },
  { flag: '🇯🇵', label: '日本語', value: 'ja' },
  { flag: '🇮🇩', label: 'Basa Jawa', value: 'jv' },
  { flag: '🇮🇳', label: 'ಕನ್ನಡ', value: 'kn' },
  { flag: '🇰🇿', label: 'Қазақша', value: 'kk' },
  { flag: '🇰🇪', label: 'Kiswahili', value: 'sw' },
  { flag: '🇰🇷', label: '한국어', value: 'ko' },
  { flag: '🇱🇦', label: 'ພາສາລາວ', value: 'lo' },
  { flag: '🇱🇻', label: 'Latviešu', value: 'lv' },
  { flag: '🇱🇹', label: 'Lietuvių', value: 'lt' },
  { flag: '🇲🇬', label: 'Malagasy', value: 'mg' },
  { flag: '🇲🇾', label: 'Bahasa Melayu', value: 'ms' },
  { flag: '🇮🇳', label: 'മലയാളം', value: 'ml' },
  { flag: '🇲🇹', label: 'Malti', value: 'mt' },
  { flag: '🇳🇵', label: 'नेपाली', value: 'ne' },
  { flag: '🇳🇬', label: 'Igbo', value: 'ig' },
  { flag: '🇳🇬', label: 'Yorùbá', value: 'yo' },
  { flag: '🇳🇴', label: 'Norsk', value: 'no' },
  { flag: '🇮🇳', label: 'ଓଡ଼ିଆ', value: 'or' },
  { flag: '🇵🇰', label: 'اردو', value: 'ur' },
  { flag: '🇮🇳', label: 'ਪੰਜਾਬੀ', value: 'pa' },
  { flag: '🇵🇱', label: 'Polski', value: 'pl' },
  { flag: '🇧🇷', label: 'Português', value: 'pt' },
  { flag: '🇷🇴', label: 'Română', value: 'ro' },
  { flag: '🇷🇺', label: 'Русский', value: 'ru' },
  { flag: '🇷🇼', label: 'Kinyarwanda', value: 'rw' },
  { flag: '🇸🇦', label: 'العربية', value: 'ar-SA' },
  { flag: '🇷🇸', label: 'Srpski', value: 'sr' },
  { flag: '🇸🇰', label: 'Slovenčina', value: 'sk' },
  { flag: '🇸🇮', label: 'Slovenščina', value: 'sl' },
  { flag: '🇸🇴', label: 'Soomaali', value: 'so' },
  { flag: '🇿🇦', label: 'Sesotho', value: 'st' },
  { flag: '🇿🇦', label: 'Zulu', value: 'zu' },
  { flag: '🇪🇸', label: 'Español', value: 'es' },
  { flag: '🇱🇰', label: 'සිංහල', value: 'si' },
  { flag: '🇸🇩', label: 'العربية السودانية', value: 'ar-SD' },
  { flag: '🇸🇪', label: 'Svenska', value: 'sv' },
  { flag: '🇮🇳', label: 'தமிழ்', value: 'ta' },
  { flag: '🇮🇳', label: 'తెలుగు', value: 'te' },
  { flag: '🇹🇯', label: 'Тоҷикӣ', value: 'tg' },
  { flag: '🇹🇭', label: 'ภาษาไทย', value: 'th' },
  { flag: '🇨🇳', label: 'བོད་སྐད།', value: 'bo' },
  { flag: '🇹🇷', label: 'Türkçe', value: 'tr' },
  { flag: '🇹🇲', label: 'Türkmençe', value: 'tk' },
  { flag: '🇺🇦', label: 'Українська', value: 'uk' },
  { flag: '🇺🇿', label: 'Oʻzbekcha', value: 'uz' },
  { flag: '🇻🇳', label: 'Tiếng Việt', value: 'vi' },
  { flag: '🏴󠁧󠁢󠁷󠁬󠁳󠁿', label: 'Cymraeg', value: 'cy' },
  { flag: '🇾🇪', label: 'اليمنية', value: 'ar-YE' },
]
